 - hosts: webservers
   become: true
   become_user: root
   vars:
    repo_name: https://github.com/srujanakasu/myansible.git
    dest_name: /tmp/gitrep
   tasks:
   - name: install docker
     yum: name=docker state=present
   - name: install git
     yum: name=git state=present
   - name: start docker
     service: name=docker state=started
   - name: clone repo from git
     git: repo={{repo_name}} dest={{dest_name}}
   - name: build docker file
     command: chdir={{dest_name}} docker build -t ansibleimage .
   - name: run image to create container
     command: docker run -d -P ansibleimage
